### ISSUE TITLE
ahash?

### ISSUE THREAD

**Issue by jianshu93** [sundy-li/simple_hll#2]
Hi Simple HLL team,

Is there a reason why ahash was used (I know ahash is fast and CoS attack resistant) but not xxh3 (rust version of xxhash) or wyhash-rs.

Thanks,

Jianshu

**Comment by sundy-li** [comment]
Hi, I just knew that ahash is fast so I used it.

I don't think there will be much more difference to switch to another hash crate.
But fixed seed must be used to keep the result stable.

**Comment by jianshu93** [comment]
Hi @sundy-li,

Yes the seed must be fixed: 

use xxh3;
/// Fixed seed for xxHash
const SEED: u64 = 0x1A2B3C4D5E6F7856_u64;
pub fn add_object<T: Hash>(&mut self, obj: &T) {
    let hash = xxh3::hash64_with_seed(obj, SEED);
    self.add_hash(hash);
}

In the case for speed, xxh3 in Rust is neon/sse or AVX2 supported and should be much faster according to this benchmark here (although it was in C++): https://xxhash.com/doc/v0.8.2/index.html

Not sure whehter it is worthwhile to add it. 

Thanks,

Jianshu

**Comment by sundy-li** [comment]
We can support it with feature gate I think. 

But the default hash must be ahash to keep compatible wth before.

Can you submit a pr to support this ?

**Comment by sundy-li** [comment]
cc @LucaCappelletti94  @jianshu93 
In latest version of https://crates.io/crates/simple_hll, there are two ways to use custom hash algorithm.

1. 
You can build hash by yourself and call:  
```
let hash = ...;
hll.add_hash(hash)
```

2. you can implement `simple_hll::Hasher` trait and call:

```

 use core::hash::{BuildHasher, Hash};
  #[derive(Default)]
  struct XXH3;
  impl crate::Hasher for XXH3 {
      fn hll_hash<T: Hash>(x: T) -> u64 {
          let builder = xxhash_rust::xxh3::Xxh3Builder::default();
          builder.hash_one(x)
      }
  }


hll.add_object_by_hasher::<XXH3, H>(object)
```
